name: time-shift-validation
channels:
    - defaults
    - anaconda
    - conda-forge
dependencies:
    - python=3.7.10
    - pip
    - pvlib=0.9.4
    - numpy
    - seaborn=0.11.1
    - matplotlib=3.3.4
    - ruptures=1.1.4
    - pandas=1.3.5
    - pip:
        - solar_data_tools==0.5.4
        - pvanalytics==0.1.3