name: time-shift-validation
channels:
    - defaults
    - anaconda
    - conda-forge
dependencies:
    - python= 3.10.11
    - pip
    - pvlib=0.9.4
    - numpy
    - seaborn=0.11.1
    - matplotlib=3.7.1
    - ruptures=1.1.7
    - pandas=1.5.3
    - pip:
        - solar_data_tools==0.7.0
        - pvanalytics==0.1.3